name: Build and Push to ECR
run-name: Build and Push for ${{ github.ref }}
on:
  push:
    branches:
      - feature/obsrv-service
    tags:
      - "*"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: "extractor"
            target: "extractor-image"
          - image: "preprocessor"
            target: "preprocessor-image"
          - image: "denormalizer"
            target: "denormalizer-image"
          - image: "transformer"
            target: "transformer-image"
          - image: "dataset-router"
            target: "dataset-router-image"
          - image: "unified-pipeline"
            target: "unified-image"
          - image: "cache-indexer"
            target: "cache-indexer-image"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get build number
        id: build-number
        run: echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Build ${{matrix.image}} docker image and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          target: ${{matrix.target}}
          push: true
          tags: |
            522814700227.dkr.ecr.us-east-1.amazonaws.com/lms_sb_obsrv_core:${{matrix.image}}-latest-${{ steps.build-number.outputs.BUILD_NUMBER }}
